apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_DB}
    user: ${INFLUXDB_READ_USER}
    secureJsonData:
      password: ${INFLUXDB_READ_USER_PASSWORD}
    jsonData:
      httpMode: GET
      keepCookies: []
    isDefault: true
    editable: true